### ISSUE TITLE
application can never boot with undefined `ENABLE_CHECKSUM`

### ISSUE THREAD

**Issue by diggit** [davidgfnet/stm32-dfu-bootloader#12]
Not defining `ENABLE_CHECKSUM` causes `imagesize = 0`.
later follows code...
 ```c
		uint32_t xorv = 0xB4DC0FEE;
		for (unsigned i = 0; i < imagesize; i++) // compiler knows, there will be 0 iterations
			xorv ^= base_addr[i];

		if (xorv == 0) { // this branch can never happen with zero iterations of the loop above
			//... unreachable code, including jump to app
		}
```
"checksum" part of code should also be disabled when `ENABLE_CHECKSUM` is not defined.

**Comment by fa1ke5** [comment]
Мало того, эта часть когда принципиально не работает, попытка использовать чексумму вызовет невозможность запуска основной программы

**Comment by davidgfnet** [comment]
I just pushed d11fbc82989b5fb01e5dd8146b3410464b00efde which should fix it. Thanks for the report, I missed it completely when I updated the checksum function!
