### ISSUE TITLE
to upgrade an application, i must upgrade it twice

### ISSUE THREAD

**Issue by cqc-elycio** [davidgfnet/stm32-dfu-bootloader#13]
if i want to upgrade an app(app already exists)， i must upgrade it twice.
the first time i program the new app, bootloader only erase flash. before try it again， i must reconnect  the  device
The second time it was successfully written.

-  OS ：windows 
- windows application : dfu-util.exe

i can`t fix this , can you help me？ Thank you very much！

**Comment by davidgfnet** [comment]
Hey, you are right! This happens indeed. Never noticed in the past due to using SAFE_WRITE which does mass erases and seems not to suffer from this?
Anyway I sent out a fix. Took me a while to figure it out!

**Comment by cqc-elycio** [comment]
> Hey, you are right! This happens indeed. Never noticed in the past due to using SAFE_WRITE which does mass erases and seems not to suffer from this? Anyway I sent out a fix. Took me a while to figure it out!

thank you very much！
