### ISSUE TITLE
DFU & Interrupts

### ISSUE THREAD

**Issue by jamesle-0812** [davidgfnet/stm32-dfu-bootloader#7]
Hi there, I'm interested in your works which can help me get rid of st-link. However I wonder whether your project supports interrupts mode. I have tried a few dfu bootloaders and both of them didn't support the mode. I have talked to an expert and he said that the code should be reprogrammed NVIC default address to work with the new vector table. Besides, do you mind to compile a .bin file and upload it with some basic instructions? It would be helpful to a beginner like me. Thanks in advance!

**Comment by davidgfnet** [comment]
The bootloader does indeed reprogram the base VTOR to the user table so that interrupts work.
The stack pointer is also read from there.
