### ISSUE TITLE
License

### ISSUE THREAD

**Issue by t-8ch** [davidgfnet/stm32-dfu-bootloader#8]
I couldn't find a license specified in the repository.
Would you mind adding licensing information?

Thanks!

**Comment by davidgfnet** [comment]
Just added it, since I copied a ton of stuff from opencm3, I'd say this is a derived work, so I'm adding the GPL3 license (although it could also work with LGPL3 since opencm3 has both, but I'm not sure how the lesser license works with firmwares :P)
Hope this helps!
Thanks for bringing it up!

**Comment by t-8ch** [comment]
Thanks!
